export const SET_USER_ACCESS_TOKEN = "UPDATE_USER";
export const SET_USER_SPOTIFY_DATA = "SET_USER_SPOTIFY_DATA";
export const UPDATE_TOP_TRACKS = "UPDATE_TOP_TRACKS";
export const UPDATE_RECOMMENDATION_PARAM = "UPDATE_RECOMMENDATION_PARAM";
export const CLEAR_RECOMMENDATION_PARAM = "CLEAR_RECOMMENDATION_PARAM";
