export const SET_USER_ACCESS_TOKEN = "UPDATE_USER";
export const SET_USER_SPOTIFY_DATA = "SET_USER_SPOTIFY_DATA";
export const UPDATE_TOP_TRACKS = "UPDATE_TOP_TRACKS";
export const ADD_SELECTED_TRACK = "ADD_SELECTED_TRACK";
export const REMOVE_SELECTED_TRACK = "REMOVE_SELECTED_TRACK";
export const ADD_RECOMMENDED_TRACKS = "ADD_RECOMMENDED_TRACKS";
export const UPDATE_RECOMMENDATION_PARAM = "UPDATE_RECOMMENDATION_PARAM";
export const CLEAR_RECOMMENDATION_PARAM = "CLEAR_RECOMMENDATION_PARAM";
